### ISSUE TITLE
How to run with USB Logitech Camera

### ISSUE THREAD

**Issue by hungnm2014** [SteveMacenski/jetson_nano_detection_and_tracking#15]
Dear Steve
I connected with a USB Logitech Camera and use Chese webcame booth app on Nano Jetson . Camera run well, but when i run with this project, camera not display.
How to use USB camera
Thanks

**Comment by SteveMacenski** [comment]
I have not supported general USB cameras, only MIPI cameras that should be used. You can easily fork and modify the camera script to use a camera capture rather than gstreamer. 

But this project does not intend to support USB cameras since MIPI are higher quality and lower overhead to operate for embedded applications (and more reliable)

**Comment by hungnm2014** [comment]
Dear @SteveMacenski 
Thanks you so much!

**Comment by AstroUKN** [comment]
> Dear @SteveMacenski
> Thanks you so much!

Hi, did you suceed changing the script with an USB camera, please ? 

Thank you !
